source homeworkManagerSqlFile/table_courses.sql;
source homeworkManagerSqlFile/table_homeworks.sql;
source homeworkManagerSqlFile/table_students.sql;
source homeworkManagerSqlFile/table_haveCourse.sql;
source homeworkManagerSqlFile/table_doHomework.sql;